# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculdora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    valor1=0
    op = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.btn_porcentagem = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("%"))
        self.btn_porcentagem.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_porcentagem.setFont(font)
        self.btn_porcentagem.setObjectName("btn_porcentagem")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("C"))
        self.btn_clear.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.divisao())
        self.btn_div.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.btn_voltar = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.remove_it())
        self.btn_voltar.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setObjectName("btn_voltar")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it("9"))
        self.btn_9.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("7"))
        self.btn_7.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("8"))
        self.btn_8.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.multiplicao())
        self.btn_mul.setGeometry(QtCore.QRect(275, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_mul.setFont(font)
        self.btn_mul.setObjectName("btn_mul")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("6"))
        self.btn_6.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("4"))
        self.btn_4.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("5"))
        self.btn_5.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.subtracao())
        self.btn_sub.setGeometry(QtCore.QRect(275, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_sub.setFont(font)
        self.btn_sub.setObjectName("btn_sub")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("1"))
        self.btn_1.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_soma = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.soma())
        self.btn_soma.setGeometry(QtCore.QRect(275, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_soma.setFont(font)
        self.btn_soma.setObjectName("btn_soma")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("3"))
        self.btn_3.setGeometry(QtCore.QRect(190, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("2"))
        self.btn_2.setGeometry(QtCore.QRect(100, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.btn_seila = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.plus_minus_it())
        self.btn_seila.setGeometry(QtCore.QRect(10, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_seila.setFont(font)
        self.btn_seila.setObjectName("btn_seila")
        self.btn_igual = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.result())
        self.btn_igual.setGeometry(QtCore.QRect(275, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_igual.setFont(font)
        self.btn_igual.setObjectName("btn_igual")
        self.btn_ponto = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.dot_it())
        self.btn_ponto.setGeometry(QtCore.QRect(190, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_ponto.setFont(font)
        self.btn_ponto.setObjectName("btn_ponto")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("0"))
        self.btn_zero.setGeometry(QtCore.QRect(100, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_zero.setFont(font)
        self.btn_zero.setObjectName("btn_zero")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
    def result(self):
        global op
        if op == "+":
            valor2=float(self.outputLabel.text())
            resultado = valor1 + valor2
            resultado = str(resultado)
            self.outputLabel.setText(resultado)
            op=""
        elif op =="-":
            valor2=float(self.outputLabel.text())
            resultado = valor1 - valor2
            resultado = str(resultado)
            self.outputLabel.setText(resultado)
            op=""
        elif op == "/":
            valor2=float(self.outputLabel.text())
            resultado = valor1 / valor2
            resultado = str(resultado)
            self.outputLabel.setText(resultado)
            op=""
        elif op == "*":
            valor2=float(self.outputLabel.text())
            resultado = valor1 * valor2
            resultado = str(resultado)
            self.outputLabel.setText(resultado)
            op=""
        else:
            pass
        
    def soma(self):
        global valor1
        global op
        valor1 = float(self.outputLabel.text())
        op = "+"
        self.outputLabel.setText("")
        
    def subtracao(self):
        global valor1
        global op
        valor1 = float(self.outputLabel.text())
        op = "-"
        self.outputLabel.setText("")
            
    def divisao(self):
        global valor1
        global op
        valor1 = float(self.outputLabel.text())
        op = "/"
        self.outputLabel.setText("")
    
    def multiplicao(self):
        global valor1
        global op
        valor1 = float(self.outputLabel.text())
        op = "*"
        self.outputLabel.setText("")    
    
    
    def plus_minus_it(self):
        screen = self.outputLabel.text()
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-",""))
        else:
            self.outputLabel.setText(f"-{screen}")
    
    #Remove o ultimo digito
    def remove_it(self):
        valor = self.outputLabel.text()
        self.outputLabel.setText(valor[:-1])
        
        
     #Adiciona decimal   
    def dot_it(self):
        screen = self.outputLabel.text()
        
        if  "." in screen:
            pass
        else:
            self.outputLabel.setText(f'{screen}.')
        
    def press_it(self, pressed):
        #Limpa o display
        if  pressed == "C":
            self.outputLabel.setText("0")
        else:
            #Remove o zero a esquerda
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            #Concatena o botao pressionado 
            self.outputLabel.setText(f" {self.outputLabel.text()}{pressed}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.btn_porcentagem.setText(_translate("MainWindow", "%"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_voltar.setText(_translate("MainWindow", "<<"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_mul.setText(_translate("MainWindow", "x"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_soma.setText(_translate("MainWindow", "+"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_seila.setText(_translate("MainWindow", "+/-"))
        self.btn_igual.setText(_translate("MainWindow", "="))
        self.btn_ponto.setText(_translate("MainWindow", "."))
        self.btn_zero.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
